excel_save_location = 'C:/Users/astor/Desktop/agora/Clientes/UOM/PRUEBA/A.xlsx'
app_Location = 'C:/Users/astor/Desktop/agora/Clientes/UOM/batman Frec y App UOM Dic 25.xlsx'
ppt_template_path = 'C:/Users/astor/Desktop/agora/Clientes/UOM/Template UOM.pptx'
ppt_export_location = 'C:/Users/astor/Desktop/agora/Clientes/UOM/PRUEBA/B.pptx'
Titulos = 'C:/Users/astor/Desktop/agora/Clientes/UOM/Titulos UOM.xlsx'
